parser: babel-eslint

extends:
  - airbnb
  - "plugin:prettier/recommended"
settings:
  import/core-modules:
    - styled-jsx
    - styled-jsx/css
    - react

env:
  browser: true
  node: true

rules:
  prettier/prettier: error

  # useless
  import/no-unresolved: off # webpack paths (./image?resize) break this
  jsx-a11y/label-has-associated-control: off
  jsx-a11y/label-has-for: off
  no-restricted-syntax: [off, "BinaryExpression[operator='in']"]
  no-return-assign: [error, except-parens]
  no-underscore-dangle: off
  no-unused-vars: [error, { argsIgnorePattern: "^_" }]
  react/jsx-closing-tag-location: off
  react/jsx-filename-extension: off
  react/jsx-one-expression-per-line: off
  react/jsx-wrap-multilines: off
  react/react-in-jsx-scope: off

  # possibly useful
  react/no-unescaped-entities: off
  react/no-danger: off
  jsx-a11y/click-events-have-key-events: off
  jsx-a11y/no-static-element-interactions: off
  react/forbid-prop-types: off
  jsx-a11y/alt-text: off
